### ISSUE TITLE
Customizing `blockHighlighter.background` doesn't work

### ISSUE THREAD

**Issue by mateuszlisowsky** [the-e3n/block-popper#1]
Hi,

I really like the extension idea and how it works, but I am not a fan of default color. Unfortunately, provided option added to user settings (settings.json) - `blockHighlighter.background` doesn't work.

Is there something I am doing wrong?

**Comment by the-e3n** [comment]
Hi @FoxSaysDerp ,
Sorry for the issue I think I somehow messed up the names of the settings when pushing. I will be pushing an update as soon as possible.

**Comment by the-e3n** [comment]
Hi @FoxSaysDerp 
Updated the extension it should reflect in vscode now. Please update and it and check if the issue is resolved
Also please share your preferred colors here. So i can make a preset of some sort for new users.
